apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS demodb;
    USE demodb;
    CREATE TABLE IF NOT EXISTS users (
      id INT AUTO_INCREMENT PRIMARY KEY,
      name VARCHAR(100),
      email VARCHAR(100),
      age INT 
    );

    INSERT INTO users (name, email, age)
    VALUES ('jatin', 'admin@test.com', 26);
