name: Node MySQL CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      # 1Ô∏è‚É£ Checkout repository
      - name: Checkout source code
        uses: actions/checkout@v4

      # 2Ô∏è‚É£ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # 3Ô∏è‚É£ Install Node dependencies (backend directory)
      - name: Install dependencies
        working-directory: backend
        run: npm ci

      # # 4Ô∏è‚É£ Run tests (backend directory)
      # - name: Run unit tests
      #   working-directory: backend
      #   run: npm test1

      # 5Ô∏è‚É£ Login to Docker Hub
      # - name: Login to Docker Hub
      #   run: |
      #     echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login \
      #       -u ${{ secrets.DOCKERHUB_USERNAME }} \
      #       --password-stdin
      - name: Login to Docker Hub
        run: |
          echo "Omnamahshivay@44" | docker login \
            -u "jatin44" \
      
      # 6Ô∏è‚É£ Build Docker image (Dockerfile inside backend)
      - name: Build Docker image
        run: |
          docker build \
            -t jatin44/node-app01:${{ github.sha }} \
            backend

      # 7Ô∏è‚É£ Push Docker image
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/node-app01:${{ github.sha }}

      # 8Ô∏è‚É£ Install Helm
      - name: Install Helm
        uses: azure/setup-helm@v4

      # # 9Ô∏è‚É£ Lint Helm charts
      # - name: Helm lint
      #   run: |
      #     helm lint helm/nodejs
      #     helm lint helm/mysql

      # # üîü Update image tag in Helm values
      # - name: Update Helm image tag
      #   run: |
      #     sed -i "s/tag:.*/tag: \"${{ github.sha }}\"/" helm/nodejs/values.yaml

      # # 1Ô∏è‚É£1Ô∏è‚É£ Commit Helm changes (GitOps handoff)
      # - name: Commit Helm changes
      #   run: |
      #     git config user.name "github-actions"
      #     git config user.email "actions@github.com"
      #     git add helm/nodejs/values.yaml
      #     git commit -m "ci: update node-app image to ${{ github.sha }}"
      #     git push
